# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Software', folder: 'pages', file: 'software.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://ca.linkedin.com/in/sylvain-white-dev'}

# Customize site text
pagination:
  next_page: 'Suivantes'
  previous_page: 'Précédentes'

sharing_button_prompt: 'Partagez avec vos amis!'

related_posts: '<br/><h2>Autres rubriques associées<h2>'

post_date_prefix: 'Rubrique écrite le'
